2021-06-19 20:35:41.525 [error] <0.267.0> Failed to start Ranch listener http in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,12580}]) for reason eaddrinuse (address already in use)
2021-06-19 20:35:41.540 [error] <0.267.0> CRASH REPORT Process <0.267.0> with 0 neighbours exited with reason: {listen_error,http,eaddrinuse} in ranch_acceptors_sup:listen_error/5 line 66
2021-06-19 20:35:41.540 [error] <0.265.0> Supervisor {<0.265.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link(http, ranch_tcp) at undefined exit with reason {listen_error,http,eaddrinuse} in context start_error
2021-06-19 20:35:41.540 [error] <0.264.0> Supervisor chatroom_sup had child connection started with connection:start_link() at undefined exit with reason {'EXIT',{{badmatch,{error,eaddrinuse}},[{connection,start_link,0,[{file,"/home/xgame/chatroom/apps/chatroom/src/connection.erl"},{line,16}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,...},...]}} in context start_error
2021-06-19 20:35:41.541 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,connection,{'EXIT',{{badmatch,{error,eaddrinuse}},[{connection,start_link,0,[{file,"/home/xgame/chatroom/apps/chatroom/src/connection.erl"},{line,16}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,...},...]}}}},...} in application_master:init/4 line 138
2021-06-19 20:35:41.547 [info] <0.43.0> Application chatroom exited with reason: {{shutdown,{failed_to_start_child,connection,{'EXIT',{{badmatch,{error,eaddrinuse}},[{connection,start_link,0,[{file,"/home/xgame/chatroom/apps/chatroom/src/connection.erl"},{line,16}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,...},...]}}}},...}
2021-06-19 20:35:41.547 [info] <0.43.0> Application jiffy exited with reason: stopped
2021-06-19 20:35:41.547 [info] <0.43.0> Application xmerl exited with reason: stopped
2021-06-19 20:35:41.547 [info] <0.43.0> Application cowboy exited with reason: stopped
2021-06-19 20:35:41.548 [info] <0.43.0> Application ranch exited with reason: stopped
2021-06-19 20:35:41.548 [info] <0.43.0> Application cowlib exited with reason: stopped
2021-06-19 20:48:47.514 [error] <0.288.0>@connection:init CRASH REPORT Process <0.288.0> with 0 neighbours crashed with reason: call to undefined function connection:init(#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accep...">> => ...,...},...}, [])
2021-06-19 20:48:47.520 [error] <0.241.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.287.0>,1,<0.288.0>,undef,[{connection,init,[#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"127.0.0.1:12580">>,<<"user-agent">> => <<"curl/7.29.0">>},host => <<"127.0.0.1">>,host_info => undefined,method => <<"GET">>,path => <<"/gate_status">>,path_info => undefined,peer => {{127,0,0,1},51410},pid => <0.287.0>,port => 12580,qs => <<>>,ref => http,scheme => <<"http">>,sock => {{127,...},...},...},...],...},...]]},...}}
2021-06-19 20:52:31.475 [error] <0.300.0>@connection:init CRASH REPORT Process <0.300.0> with 0 neighbours crashed with reason: call to undefined function connection:init(#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accep...">> => ...,...},...}, [])
2021-06-19 20:52:31.476 [error] <0.241.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.297.0>,2,<0.300.0>,undef,[{connection,init,[#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"10.1.21.153:12580">>,<<"referer">> => <<"http://10.1.21.153:12580/status">>,<<"u...">> => ...},...},...],...},...]]},...}}
